### ISSUE TITLE
Add clinvar to genome nexus variant page

### ISSUE THREAD

**Issue by inodb** [genome-nexus/genome-nexus#506] opened 2021-04-14 15:12 UTC
I believe we still have clinvar from myvariant.info on the genome nexus variant page. Can we use the new clinvar data?

**Comment by leexgh** [comment] 2021-05-25 15:21
Duplicate of https://github.com/genome-nexus/genome-nexus/issues/508

**Closed by leexgh** 2021-05-25 15:21 UTC
Labels: manuscript
